[package]
name = "carton"
version = "0.1.0"
edition = "2021"

# Ignore all test_data/ folders
exclude = ["test_data/"]

[dependencies]
serde = { version = "1.0", features = ["derive"] }
ndarray = { version = "0.15", features = ["serde"] }
tokio = { version = "1", features = ["full"] }
tempfile = "3.3.0"
bincode = "1.3.3"
dashmap = "5.4.0"
clap = { version = "4.0.29", features = ["derive"] }
carton-macros = { path = "../carton-macros" }
chrono = {version = "0.4.23", features = ["serde"]}
toml = "0.5"
semver = {version = "1.0.16", features = ["serde"]}
target-lexicon = "0.12.5"