only_if: $CIRRUS_TAG == '' && ($CIRRUS_PR != '' || $CIRRUS_BRANCH == 'main')

env:
  CARGO_TERM_COLOR: always

# linux_task:
#   name: Native Build aarch64-unknown-linux-gnu
#   arm_container:
#     dockerfile: ci/ci.dockerfile
#     cpu: 4
#     memory: 16G
#   target_cache:
#     folder: target
#     fingerprint_script:
#       - rustc --version
#       - cat Cargo.lock
#   build_and_test_script:
#     - pip3 install toml maturin==0.14.13
#     - python3 ci/build.py --target aarch64-unknown-linux-gnu
#   before_cache_script: rm -rf $CARGO_HOME/registry/index

macos_task:
  name: Native Build aarch64-apple-darwin
  macos_instance:
    image: ghcr.io/cirruslabs/macos-ventura-xcode:14.2
  symlink_xcode_script:
    - ln -s /Applications/Xcode-14.2.0.app /Applications/Xcode.app
    - ls -alh /Applications/
  setup_script:
    - curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y --profile minimal --default-toolchain stable
  build_and_test_script:
    - source $HOME/.cargo/env
    - pip3 install toml maturin==0.14.13
    - python3 ci/build.py --target aarch64-apple-darwin
  timings_artifacts:
    path: "target/cargo-timings/*"
