[package]
name = "fetch-deps"
version = "0.0.1"
edition = "2021"
publish = false

[dependencies]
tokio = { version = "1", features = ["full"] }
carton-utils = { path = "../carton-utils" }
tempfile = "3.3.0"
semver = {version = "1.0.16"}