[build]

# This lets us use tokio's tracing feature (which we need for tokio-console)
rustflags = ["--cfg", "tokio_unstable"]

# Set a default target so that build caches are saved correctly when switching targets
# https://doc.rust-lang.org/cargo/guide/build-cache.html
target = ["x86_64-unknown-linux-gnu"]

[env]
LIBTORCH = {value = "./libtorch", relative = true}
LIBTORCH_BYPASS_VERSION_CHECK = {value = "true"}
XLA_EXTENSION_DIR = {value = "./xla_extension", relative = true}