version: '2'
services:
  x86_64:
    build:
      context: ../
      dockerfile: ci/ci.dockerfile
      args:
        - BUILD_TARGET=x86_64
    working_dir: /app
    volumes:
      - ..:/app
    environment:
      - RUSTC_WRAPPER=/sccache/sccache
      - SCCACHE_BUCKET=carton-build-cache
      - SCCACHE_REGION=us-east-1
  arm64:
    build:
      context: ../
      dockerfile: ci/ci.dockerfile
      args:
        - BUILD_TARGET=aarch64
    working_dir: /app
    volumes:
      - ..:/app
    environment:
      - RUSTC_WRAPPER=/sccache/sccache
      - SCCACHE_BUCKET=carton-build-cache
      - SCCACHE_REGION=us-east-1