name: CI

on:
  push:
    branches:
      - main
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  formatting:
    name: rustfmt
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.ZIPFS_READ }}
          submodules: recursive
      - run: cargo fmt --check
  build_and_test_native:
    name: Native Build ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.ZIPFS_READ }}
          submodules: recursive
      - run: cargo build --verbose
      - run: cargo test --verbose
      - name: Upload `carton_logs` on failure
        if: ${{ failure() }}
        uses: actions/upload-artifact@v3
        with:
          name: tmp_carton_logs
          path: /tmp/carton_logs
  build_wasm:
    name: WASM Build ${{ matrix.target }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          - wasm32-wasi
          - wasm32-unknown-unknown
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.ZIPFS_READ }}
          submodules: recursive
      - run: rustup target add ${{ matrix.target }}
      - run: cargo build -p carton --verbose --target ${{ matrix.target }}