name: CI

on:
  push:
    branches:
      - main
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  formatting:
    name: rustfmt
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.ZIPFS_READ }}
          submodules: recursive
      - run: cargo fmt --check
  # build_and_test_native:
  #   name: Native Build ${{ matrix.os }}
  #   runs-on: ${{ matrix.os }}
  #   container:
  #     # TODO: only on linux
  #     image: vpanyam/manylinux2014-rust-python310:x86_64
  #   strategy:
  #     matrix:
  #       include:
  #         - os: ubuntu-latest
  #           target: x86_64-unknown-linux-gnu
  #         # For now, don't run macos builds on every commit.
  #         # TODO: reenable this when the repo is public
  #         # - os: macos-latest
  #         #   target: x86_64-apple-darwin
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v3
  #       with:
  #         token: ${{ secrets.ZIPFS_READ }}
  #         submodules: recursive
  #     - run: rustup default stable
  #     - uses: Swatinem/rust-cache@v2
  #     - run: pip3 install toml maturin==0.14.13
  #     - run: python3 ci/build.py --target ${{ matrix.target }}
  #     - name: Upload `carton_logs` on failure
  #       if: ${{ failure() }}
  #       uses: actions/upload-artifact@v3
  #       with:
  #         name: tmp_carton_logs
  #         path: /tmp/carton_logs
  build_wasi:
    name: WASM Build wasm32-wasi
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.ZIPFS_READ }}
          submodules: recursive
      - run: rustup target add wasm32-wasi
      - run: cargo build -p carton --verbose --target wasm32-wasi
  build_wasm:
    name: WASM Build wasm32-unknown-unknown
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.ZIPFS_READ }}
          submodules: recursive
      - run: rustup target add wasm32-unknown-unknown
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm install -g wasm-pack yarn@1.22.19
      - run: >
          cd source/carton-bindings-wasm && ./build.sh &&
          cd tests && yarn install && node basic.js
